# Generated by Django 5.1.1 on 2025-03-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('jobs', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='interviews.interview'),
        ),
        migrations.AddField(
            model_name='reviewquestion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.reviewquestion'),
        ),
    ]
